name: zerotk.xml_factory
module: zerotk.xml_factory
namespace: zerotk
path: zerotk/reraiseit
author: Alexandre Andrade, Diogo de Campos
author_email: kaniabi@gmail.com, campos.ddc@gmail.com
development_status: 5 - Production/Stable
short_description: XML/Dict/Json Generator.
long_description: XMl Factory is a simple XMl writer that uses dict syntax to write files.
install_requires:
  - six
keywords:
  - xml
  - dict
  - json
  - generator
  - pretty
tests_require:
  - pytest
  - coverage
  - cogapp
  - pytest-datadir
